-- =========================================================
-- DISTRIBUTED RETAIL POS - STORE SCHEMA (RELAXED FK)
-- (Run this on Store A & Store B)
-- =========================================================

-- EXPLANATION:
-- We are removing the Foreign Key constraint to 'users' table
-- because Authentication is Centralized. The Store DB won't constantly
-- have all the latest users synced, so strict FK would break writes.

DROP TABLE IF EXISTS transaction_items CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS cash_shifts CASCADE; -- Resetting to be safe
DROP TABLE IF EXISTS users CASCADE;

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. PRODUCTS
CREATE TABLE products (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode         VARCHAR(50) UNIQUE NOT NULL,
    name            VARCHAR(200) NOT NULL,
    price           NUMERIC(15, 2) NOT NULL,
    tax_rate        NUMERIC(5, 2) DEFAULT 0,
    category        VARCHAR(50),
    stock           INT DEFAULT 0,
    is_active       BOOLEAN DEFAULT TRUE,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 3. USERS (Optional Local Cache)
CREATE TABLE IF NOT EXISTS users (
    user_id         UUID PRIMARY KEY,
    username        VARCHAR(50),
    full_name       VARCHAR(100),
    role            VARCHAR(20)
);

-- 4. CASH SHIFTS
CREATE TABLE IF NOT EXISTS cash_shifts (
    shift_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       INT NOT NULL,
    user_id         UUID, -- REMOVED REFERENCES for distributed flexibility
    start_time      TIMESTAMPTZ DEFAULT NOW(),
    end_time        TIMESTAMPTZ,
    end_cash_actual NUMERIC(15, 2) DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'OPEN'
);

-- 5. TRANSACTIONS
CREATE TABLE IF NOT EXISTS transactions (
    transaction_uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id        INT NOT NULL,
    shift_id         BIGINT, -- Optional ref
    user_id          UUID,   -- REMOVED REFERENCES users(user_id)
    subtotal         NUMERIC(15, 2) NOT NULL,
    total_discount   NUMERIC(15, 2) DEFAULT 0,
    tax_amount       NUMERIC(15, 2) DEFAULT 0,
    grand_total      NUMERIC(15, 2) NOT NULL,
    payment_method   VARCHAR(50),
    payment_ref      VARCHAR(100),
    cash_received    NUMERIC(15, 2) DEFAULT 0,
    change_returned  NUMERIC(15, 2) DEFAULT 0,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    synced           BOOLEAN DEFAULT FALSE
);

-- 6. TRANSACTION ITEMS
CREATE TABLE IF NOT EXISTS transaction_items (
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_uuid UUID REFERENCES transactions(transaction_uuid),
    product_id       BIGINT REFERENCES products(product_id),
    qty              INT NOT NULL,
    price_at_sale    NUMERIC(15, 2) NOT NULL,
    discount_amount  NUMERIC(15, 2) DEFAULT 0,
    subtotal         NUMERIC(15, 2) NOT NULL,
    notes            VARCHAR(100)
);

-- 7. SEED DATA
INSERT INTO products (barcode, name, price, category) VALUES
('8993005320901', 'Indomie Goreng Original', 3500, 'Food'),
('8998989300222', 'Teh Botol Sosro 250ml', 4500, 'Beverage'),
('8991001000222', 'Aqua 600ml', 3000, 'Beverage')
ON CONFLICT (barcode) DO NOTHING;

-- 8. PERMISSIONS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items ENABLE ROW LEVEL SECURITY;

-- Allow Public Access
CREATE POLICY "Public Manage Products" ON products FOR ALL USING (true);
CREATE POLICY "Public Write Transactions" ON transactions FOR ALL USING (true);
CREATE POLICY "Public Write Items" ON transaction_items FOR ALL USING (true);
