-- =========================================================
-- CENTRAL HQ - MASTER DATA SCHEMA (UNIFIED)
-- (Run this on the Central/Authentication Database)
-- =========================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. MASTER DATA TABLES

-- Branches
CREATE TABLE IF NOT EXISTS branches (
    branch_id       SERIAL PRIMARY KEY,
    branch_code     VARCHAR(20) UNIQUE NOT NULL,
    name            VARCHAR(100) NOT NULL,
    location        VARCHAR(200),
    is_active       BOOLEAN DEFAULT TRUE
);

-- Profiles (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS profiles (
    id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username        VARCHAR(50) UNIQUE,
    email           VARCHAR(100),
    role            VARCHAR(20) DEFAULT 'STAFF', 
    full_name       VARCHAR(100),
    branch_id       INT REFERENCES branches(branch_id),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- !! CRITICAL MIGRATION FIX !!
-- Ensure 'pin' column exists even if table was already created
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'pin') THEN
        ALTER TABLE profiles ADD COLUMN pin VARCHAR(6);
    END IF;
END $$;


-- Products (Global Master Catalog)
CREATE TABLE IF NOT EXISTS products (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode         VARCHAR(50) UNIQUE NOT NULL,
    name            VARCHAR(200) NOT NULL,
    price           NUMERIC(15, 2) NOT NULL,
    cost_price      NUMERIC(15, 2) DEFAULT 0,
    tax_rate        NUMERIC(5, 2) DEFAULT 0,
    category        VARCHAR(50),
    sku             VARCHAR(50),
    image_url       TEXT,
    is_active       BOOLEAN DEFAULT TRUE,
    stock           INT DEFAULT 0, 
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 3. OPERATIONAL TABLES (Migrated from Store Local DBs)

-- Cashier Shifts
CREATE TABLE IF NOT EXISTS cash_shifts (
    shift_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       INT REFERENCES branches(branch_id), 
    user_id         UUID REFERENCES auth.users(id), 
    start_time      TIMESTAMPTZ DEFAULT NOW(),
    end_time        TIMESTAMPTZ,
    start_cash      NUMERIC(15, 2) DEFAULT 0,
    end_cash_actual NUMERIC(15, 2) DEFAULT 0,
    end_cash_system NUMERIC(15, 2) DEFAULT 0,
    variance        NUMERIC(15, 2) DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'OPEN'
);

-- Transactions (Header)
CREATE TABLE IF NOT EXISTS transactions (
    transaction_uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id        INT REFERENCES branches(branch_id), 
    shift_id         BIGINT REFERENCES cash_shifts(shift_id),
    user_id          UUID REFERENCES auth.users(id), 
    subtotal         NUMERIC(15, 2) NOT NULL,
    total_discount   NUMERIC(15, 2) DEFAULT 0,
    tax_amount       NUMERIC(15, 2) DEFAULT 0,
    grand_total      NUMERIC(15, 2) NOT NULL,
    payment_method   VARCHAR(50),
    payment_ref      VARCHAR(100),
    cash_received    NUMERIC(15, 2) DEFAULT 0,
    change_returned  NUMERIC(15, 2) DEFAULT 0,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Transaction Items (Detail)
CREATE TABLE IF NOT EXISTS transaction_items (
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_uuid UUID REFERENCES transactions(transaction_uuid),
    product_id       BIGINT REFERENCES products(product_id),
    qty              INT NOT NULL,
    price_at_sale    NUMERIC(15, 2) NOT NULL,
    discount_amount  NUMERIC(15, 2) DEFAULT 0,
    subtotal         NUMERIC(15, 2) NOT NULL,
    notes            VARCHAR(100)
);

-- 4. SEED DATA

INSERT INTO branches (branch_code, name, location) VALUES
('TOKO_JKT1', 'Alfamart JKT-001 Branch', 'Jakarta'),
('TOKO_BDG1', 'Alfamart BDG-001 Branch', 'Bandung')
ON CONFLICT (branch_code) DO NOTHING;

INSERT INTO products (barcode, name, price, category) VALUES
('8993005320901', 'Indomie Goreng Original', 3500, 'Food'),
('8998989300222', 'Teh Botol Sosro 250ml', 4500, 'Beverage'),
('8991001000222', 'Aqua 600ml', 3000, 'Beverage')
ON CONFLICT (barcode) DO NOTHING;
