-- =========================================================
-- DISTRIBUTED RETAIL POS - SUPABASE SCHEMA
-- (Run this on EACH Store's Supabase Instance)
-- =========================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CORE POS TABLES

-- Users (Auth is handled by Supabase Auth, but we keep a public profile/users table for POS logic)
CREATE TABLE users (
    user_id         BIGINT PRIMARY KEY,
    username        VARCHAR(50) NOT NULL UNIQUE,
    email           VARCHAR(100), 
    pin_hash        VARCHAR(255),
    role            VARCHAR(20),
    full_name       VARCHAR(100),
    branch_id       INT,
    is_active       BOOLEAN DEFAULT TRUE
);

-- Products (Master Catalog for this Store)
CREATE TABLE products (
    product_id      BIGINT PRIMARY KEY,
    barcode         VARCHAR(50) UNIQUE NOT NULL,
    name            VARCHAR(200) NOT NULL,
    price           NUMERIC(15, 2) NOT NULL,
    tax_rate        NUMERIC(5, 2) DEFAULT 0,
    category        VARCHAR(50),
    stock           INT DEFAULT 0,
    is_active       BOOLEAN DEFAULT TRUE,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Cashier Shifts
CREATE TABLE cash_shifts (
    shift_id        BIGSERIAL PRIMARY KEY,
    branch_id       INT NOT NULL,
    user_id         BIGINT REFERENCES users(user_id),
    start_time      TIMESTAMPTZ DEFAULT NOW(),
    end_time        TIMESTAMPTZ,
    start_cash      NUMERIC(15, 2) DEFAULT 0,
    end_cash_actual NUMERIC(15, 2) DEFAULT 0,
    end_cash_system NUMERIC(15, 2) DEFAULT 0,
    variance        NUMERIC(15, 2) DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'OPEN'
);

-- Transactions (Header)
CREATE TABLE transactions (
    transaction_uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id        INT NOT NULL,
    shift_id         BIGINT REFERENCES cash_shifts(shift_id),
    user_id          BIGINT REFERENCES users(user_id),
    subtotal         NUMERIC(15, 2) NOT NULL,
    total_discount   NUMERIC(15, 2) DEFAULT 0,
    tax_amount       NUMERIC(15, 2) DEFAULT 0,
    grand_total      NUMERIC(15, 2) NOT NULL,
    payment_method   VARCHAR(50),
    payment_ref      VARCHAR(100),
    cash_received    NUMERIC(15, 2) DEFAULT 0,
    change_returned  NUMERIC(15, 2) DEFAULT 0,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Transaction Items (Detail)
CREATE TABLE transaction_items (
    item_id          BIGSERIAL PRIMARY KEY,
    transaction_uuid UUID REFERENCES transactions(transaction_uuid),
    product_id       BIGINT REFERENCES products(product_id),
    qty              INT NOT NULL,
    price_at_sale    NUMERIC(15, 2) NOT NULL,
    discount_amount  NUMERIC(15, 2) DEFAULT 0,
    subtotal         NUMERIC(15, 2) NOT NULL,
    notes            VARCHAR(100)
);

-- 3. DISTRIBUTED ORCHESTRATION TABLES (From FNB Project)

-- Command Requests (From Admin Dashboard)
CREATE TABLE command_requests (
  request_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  command_type TEXT NOT NULL, -- e.g., 'CALC', 'PING'
  payload JSONB, -- e.g., { "category": "Food", "agg_type": "SUM" }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Command Results (To Admin Dashboard)
CREATE TABLE command_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id UUID REFERENCES command_requests(request_id),
  store_id TEXT NOT NULL,
  result_data JSONB, -- e.g., { "value": 500000, "agg_type": "SUM" }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. VIEW FOR ANALYTICS (Simplifies Python Node Queries)
CREATE OR REPLACE VIEW view_transaction_details AS
SELECT 
    t.transaction_uuid,
    t.branch_id,
    t.created_at,
    t.grand_total,
    ti.qty,
    ti.subtotal as item_total,
    p.category,
    p.name as product_name
FROM transactions t
JOIN transaction_items ti ON t.transaction_uuid = ti.transaction_uuid
JOIN products p ON ti.product_id = p.product_id;